/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#define USE_BSRR		true

uint32_t *pRccAhb1enr = (uint32_t*)0x40023830;    // RCC_AHB1ENR - RCC AHB1 peripheral clock enable register
uint32_t *pGpioAModer = (uint32_t*)0x40020000;    // GPIOA_MODER - GPIO port mode register
uint32_t *pGpioAOdr   = (uint32_t*)0x40020014;    // GPIOA_ODR   - GPIO port output data register (r/w)
uint32_t *pGpioABsrr  = (uint32_t*)0x40020018;    // GPIOA_BSRR  - GPIO port bit set/reset register (high word = atomic reset, low word = atomic set)

void delay(int ms)
{
    while (ms-- > 0) {
        volatile int x = 5971;
        while (x-- > 0)
            __asm("nop");
    }
}

int main(void)
{
	*pRccAhb1enr |= (1 << 0);						// set bit 0 to enable port A

	*pGpioAModer &= ~((1 << 10) | (1 << 11));	    // clear bit 10 and 11
	*pGpioAModer |= (1 << 10);					    // set bit 10

	//*pGpioAOdr |= (1 << 5);						// set bit 5 to set output to high
	*pGpioABsrr |= (1 << 5);						// set bit 5 to set output to high

    /* Loop forever */
	while(1)
	{
		delay(400);
#if USE_BSRR == false
		*pGpioAOdr ^= (1 << 5);
#elif USE_BSRR == true
		if (((*pGpioAOdr >> 5) & 0x1) == 0)
		{
			*pGpioABsrr = (1 << 5);
		}
		else
		{
			*pGpioABsrr = (1 << (16 + 5));
		}
#endif
	}

}
